### PR TITLE
Add Firmware Update and Configure HBA Docs

### PR DESCRIPTION
**Pull request by ltrager**
Update nodes-hw-scripts-field to contain docs for both hardware scripts and updating firmware or configuring HBA's with commissioning scripts.

### CODE REVIEW

**Comment by evilnick** [comment]
Was there some reason all his stuff was cut and paste into one page? It is difficult to follow now and has headings all over the place.
It doesn't really help with identifying the additions you want to make

**Comment by ltrager** [comment]
I merged the two files together because it seemed confusing to have how to write scripts and the samples in two separate places.

**Comment by roaksoax** [comment]
I agree with Lee here. It is confusing from the users perspective when it comes to reading the documentation. That said, the documentation is very hardware testing specific, but the reality of it is that it is not at all.

What lee is doing here is combining the documentation that addresses both, commissioning & hardware testing scripts.

That said, I do agree that the diff doesn't help identifying changes. What I would request is do two things:

1. Combine the docs into a single page.
2. Make the additions

or the other way around.

**Comment by roaksoax** [comment]
FWIW, I have just received feedback from several readers that this doc has actually helped them understand how this whole things works vs the previous way of presenting this information. As such, I think this document has made it easier to understand the content and I feel strongly about making this changes.

**Comment by evilnick** [comment]
That's cool. Yes, it would certainly have helped if this had been two separate PRs instead of one.

I appreciate that you may think this works better as a single page (when I said it was difficult to follow I meant because some of the headings are now wrong and the order of the content seems somewhat jumbled) 

With structural things (merging pages) it is usually better to give someone in docs a heads up beforehand - renaming and deleting pages can cause issues with versioning and navigation - e.g., these changes introduce broken links on the navigation and in other parts of the docs. I'm sure @degville can fix it up for you

**Comment by degville** [comment]
Yep, sure. I'll merge this and make the fixes

**Pull request merged**
