### PR TITLE
Added CC-BY-SA License

### PR DESCRIPTION
**Pull request by evilnick**

### CODE REVIEW

**Comment by evilnick** [comment]
Fixes #224

**Comment by pmatulis** [comment]
Didn't you earlier specify version 4 (gdoc memo)? This says version 3.

**Comment by evilnick** [comment]
Oh. I think their links are wrong. OK, leave it and I will check

**Comment by evilnick** [comment]
Hmm, no, it does say 4.0, right there at the top - are you sure you aren't reading the bit to be deleted?

**Comment by pmatulis** [comment]
Damn it. Sorry about that.

**Pull request merged**
