### PR TITLE
Update PXE/DHCP troubleshooting

### PR DESCRIPTION
**Pull request by erickeller**
This fix unlocked my situation where the MAAS UI could not really activate anymore.
and the ConditionPathExists=/var/lib/maas/dhcpd-interfaces from maas-dhcpd.service was missing

### CODE REVIEW

**Comment by jsseidel** [comment]
Hi Eric -- So, I'm told 2 things. First, I realize you're targeting 2.4 with this PR, but FYI -- this issue has been fixed in 2.5, so hopefully this fix won't be needed in the future. Second, and I haven't verified this, restarting maas-rackd should also work. Have you tried that?

**Comment by erickeller** [comment]
Well at the time I run into this issue I was using Ubuntu 18.04 repos to install Maas. There it used 2.4.

I did not try if `system restart maas-rackd` did the trick. I can just ensure that the described workaround was my last resort and did work at the end...

**Comment by jsseidel** [comment]
Yep, understood. I now have on my todo list to add something about this into the 2.4 troubleshooting guide. I'm going to start with the restarting maas-rackd fix. Please let me know if you ever run into this and that *doesn't work* and I'll make more changes. Thanks for letting me know.

**Comment by erickeller** [comment]
I will restage the production on Ubuntu 18.04 in one or two week. Will let you know if this still occurs.

**Comment by jsseidel** [comment]
Excellent. Thanks.

**Pull request closed without merging**
