### PR TITLE
Updated architectural overview for design consistency

### LINKED ISSUE #616: Update Architectural Overview diagram
The following diagram needs to be updated for design consistency with MAAS and other diagrams:

https://docs.ubuntu.com/maas/2.2/en/intro-architecture

### PR DESCRIPTION
**Pull request by degville**
I had my crayons out, so I thought I'd update this. 

fixes #616

### CODE REVIEW

**Comment by pmatulis** [comment]
- Looks like iSCSI/tgt (ephemeral images) is being replaced by HTTP in 2.3.
Ref: https://lists.ubuntu.com/archives/maas-devel/2017-August/002659.html
 - HA can be implemented in at least two ways, not necessarily with HAProxy.
 - I find the HA colour (of red) stands out unnecessarily. Especially considering that it's optional.
 - Can load balancing be included somehow without the image becoming outlandish? Probably not but just bringing it up.
 - Maybe we can include further images that cover HA and/or load balancing. So remove HA from this current image?

**Comment by degville** [comment]
Thanks for the feedback. I've removed HA because I think you're right about creating further images to explain HA and load balancing, keeping this as a more general overview.

**Comment by dshcherb** [comment]
@degville 

We need to leave the old diagram for pre-2.3 docs.

ttps://github.com/CanonicalLtd/maas-docs/pull/617/files#diff-9011e6d8f23bd19a199df81f2d5caba6

Otherwise this is going to be a bit misleading due to iSCSI usage in pre-2.3 versions. Right now if I open MAAS docs for 2.2 it will show the new diagram for 2.2.

**Comment by degville** [comment]
Thanks @dshcherb. I have a version of the new diagram with iSCSI which can link to from the earlier versions of the docs.

**Pull request merged**
